project:
  type: website
  output-dir: _site

website:
  title: "Thomas Hodges"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: cv/index.qmd
        text: CV
      - href: blog/index.qmd
        text: Blog
      - href: data/index.qmd
        text: Data
      - href: research/index.qmd
        text: Research
      - href: talks/index.qmd
        text: Talks
        
    right: 
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:tommyjhodges@gmail.com"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/TJH-RESEARCH
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/tom-hodges
        rel: me
      - text: "{{< iconify fa-brands:researchgate size=1.1em title='Research Gate' >}}"
        href: https://www.researchgate.net/profile/Thomas-Hodges-4?ev=hdr_xprf
        rel: me
      - text: "{{< ai google-scholar size=1.1em title='Google Scholar' >}}"
        href: https://scholar.google.com/citations?hl=en&authuser=3&user=wG3FltQAAAAJ
        rel: me
      - text: "{{< ai orcid size=1.1em title='ORCID' >}}"
        href: https://orcid.org/0000-0002-5184-7346
        rel: me

  page-footer:
    center: |
      <span>{{< fa brands creative-commons >}} {{< var years >}} Thomas Hodges </span>


format:
  html:
    theme:
      - html/united-custom.scss
    css: styles.css
    toc: true
    google-fonts: 
      - Oswald

editor: visual

