project:
  type: website
  output-dir: _site

website:
  title: "TJH Research"
  search: false
  navbar:
    left:
      - href: /#about
        text: About
      #- href: cv/index.qmd
      #  text: CV
      - href: /#research
        text: Research
      - href: /#contact
        text: Contact
      - href: blog/index.qmd
        text: Blog
      - href: research/index.qmd
        text: Articles, Presentations & Projects
        
  page-footer:
    center: |
      <span>{{< fa brands creative-commons >}} {{< var years >}} Thomas Hodges </span>


format:
  html:
    theme:
      - html/united-custom.scss
    css: styles.css
    toc: true
    google-fonts: 
      - Oswald

editor: visual

