[build]
  command = """
  apt-get update && apt-get install -y gdebi-core
  curl -fsSL https://quarto.org/download/latest/quarto-linux-amd64.deb -o quarto.deb
  gdebi -n quarto.deb
  quarto render
  """
  publish = "_site"
