[build]
  command = """
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.4.550/quarto-1.4.550-linux-amd64.tar.gz &&
    tar -xvzf quarto-1.4.550-linux-amd64.tar.gz &&
    ./quarto-1.4.550/bin/quarto render
  """
  publish = "_site"

[build.environment]
  QUARTO_VERSION = "1.6.42"  # or latest available version
