---
title: "‘Just leader? No, lideresa!’ Experiences of Female Leaders Working in Climate Change Disaster Risk Reduction and Environmental Sustainability in the Global South"
date: 2024-08-15
author:
  - name: Thomas J. Hodges
    orcid: 0000-0002-5184-7346
    affiliation: Center for the Advancement of Military and Emergency Services (AMES) Research, Kennesaw State University
  - name: Nilofer K. Bharwani
    orcid: 0009-0000-6078-4431
    affiliation: School of Conflict Management, Peacebuilding, and Development, Kennesaw State University
  - name: Darina Lepadatu
    #orcid:
    affiliation: School of Conflict Management, Peacebuilding, and Development, Kennesaw State University
  - name: Darlene Xiomara Rodriguez
    orcid: 0000-0001-6627-1899
    affiliation: Department of Social Work and Human Services, Kennesaw State University
categories:
  - Gender
  - Climate Change
  - Global Development
  - Management
  - Environment
pub-info:
  links:
    - name: Final version
      url: https://doi.org/10.1088/2752-5295/ad6a7a
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1088/2752-5295/ad6a7a
      icon: ai ai-zotero
doi: 10.1088/2752-5295/ad6a7a
---

## Links

-   [Paper](https://dx.doi.org/10.1088/2752-5295/ad6a7a)

## Abstract

As environmental disasters disproportionately affect women, international guidelines to address the disparity focus on the inclusion of women in disaster risk reduction programs. While inclusion is a noble pursuit, it may fall short of equitable outcomes and instead lead to tokenization. Drawing on standpoint feminism and intersectionality, the goal of this study was to investigate tensions between inclusion and equity for women working in disaster risk reduction. We interviewed women from Ecuador and Tajikistan and asked them about the ways that gender shapes their experiences working in disaster risk reduction. We found that the women reflect upon themselves as agents with various forms of privilege and disadvantage, based on their multifaceted identities and differing levels of perceived discrimination within their professions. The findings suggest that inclusion, while necessary, can fall short of its promises. We recommend that organizational guidelines make everyone responsible for fostering equitable workplaces for disaster risk reduction.

## Citation

Bharwani, N. K., Hodges, T., Lepadatu, D., & Rodriguez, D. X. (2024). ‘Just leader? No, lideresa!’ Experiences of female leaders working in climate change disaster risk reduction and environmental sustainability in the global south. *Environmental Research: Climate*, *3*(4), 045008. <https://doi.org/10.1088/2752-5295/ad6a7a>

``` bibtex
@article{BharwaniHodgesLepadatuRodriguez:2024,
    Author = {Nilofer K. Bharwani and Thomas J. Hodges and Darina Lepadatu and Darlene Xiomara Rodriguez},
    Doi = {10.1088/2752-5295/ad6a7a},
    Journal = {Environmental Research: Climate},
    Title = {‘Just leader? No, lideresa!’ Experiences of female leaders working in climate change disaster risk reduction and environmental sustainability in the global south},
    Year = {2024}}
```
