---
title: "Cleaning and Screening Messy Real-World Survey Data"
description: "You analyze the data you have, not the data you want"
author:
  - name: Thomas Hodges
    orcid: 0000-0002-5184-7346
date: 2025-06-25
categories: 
  - Data Cleansing
draft: false
---

# Summary

I have conducted dozens of surveys with employees, students, and community members. A common issue with surveys is data quality. For this project, I used cutting-edge methods to detect poor-quality survey responses. I then repeated the process for two additional surveys, resulting in clean data sets that have been used for X scientific publications. Additionally, I am drafting a paper that outlines the methods in an accessible way.

-   git hub

-   paper

-   talk

# Skills Demonstrated

1.  R Programming

<!-- -->

2.  Data Quality Assurance

3.  Survey Design and Analysis

# Real-World Applications:

-   People Analytics

-   Employee Health and Well-being

-   Employee Engagement and Satisfaction surveys

# Key Highlights

Dirty Data: Careless survey responding. Examples using R visualizations

Developing an Order of Operations

## 
