---
title: "Unlocking SSM/V success: Welcoming student service members and veterans and supporting SSM/V experiences"
date: 2022-03-10
author:
  - name: Thomas J. Hodges
    orcid: "{{< var orcid >}}"
    affiliation: School of Conflict Management, Peacebuilding and Development, Kennesaw State University
  - name: Kimberly D. Gomes
    affiliation: Kennesaw State University
  - name: Geno C. Foral
    affiliation: Kennesaw State University
  - name: Tyler L. Collette
    affiliation: Department of Psychological Science, Kennesaw State University
  - name: Brian A. Moore
    affiliation: Department of Psychological Science, Kennesaw State University
categories:
  - Higher Education
  - Reintegration
  - Veterans
pub-info:
  links:
    - name: Final version
      url: http://journals.sagepub.com/doi/10.1177/15210251221086851
      icon: fa-solid fa-scroll
    - name: Add to Zotero
      url: https://www.zotero.org/save?type=doi&q=10.1177/15210251221086851
      icon: ai ai-zotero
doi: 10.1177/15210251221086851
---

## Important links

-   [Paper](http://journals.sagepub.com/doi/10.1177/15210251221086851)

## Abstract

Helping student service members and veterans (SSM/Vs) earn a college degree is central to supporting them post-service. Yet, this generation of SSM/Vs faces challenges in higher education, including problems adapting, poor health, and administrative constraints, contributing to worsened academic outcomes and a sense of isolation on campus. This monograph synthesizes research on the challenges facing SSM/Vs. It also frames common aspects of successful programs aiding SSM/Vs as three areas for intervention: how administrators and faculty can create a welcoming campus for SSM/Vs; ways universities can create support systems for SSM/V social, health, and academic success; and engaging community partnerships to enable these efforts. Whether SSM/Vs overcome their challenges and unlock their strengths is contingent on opportunities provided within the school itself, and by its faculty, administrators, students, and community. Central to these efforts should be the goal of inclusivity enhancement, community building, and reduction of health-related dysfunction among SSM/Vs.

## Citation

``` bibtex
@article{HodgesGomesForalColletteMoore:2024,
    Author = {Thomas J. Hodges and Kimberly D. Gomes and Geno C. Foral and Tyler L. Collette and Brian A. Moore},
    Doi = {10.1177/15210251221086851},
    Journal = {Journal of College Student Retention: Research, Theory & Practice},
    Title = {Unlocking SSM/V success: Welcoming student service members and veterans and supporting SSM/V experiences},
    Year = {2024}}
```
